services:
    ctk:
        environment:
            ENTITIES: BillFormat,BillingCycleSpecification,FinancialAccount,BillingAccount,BillPresentationMedia,SettlementAccount
            TOP_LEVEL_ENTITY: accountManagement
        image: ghcr.io/tmforum-rand/ctk_docker_images/async-ctk-v5:latest
        network_mode: host
        volumes:
        - .:/app
        working_dir: /app
version: '3.8'
